# Generated by Django 5.0.7 on 2026-05-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedexpense',
            options={'ordering': ['name'], 'verbose_name': 'Despesa fixa', 'verbose_name_plural': 'Despesas fixas'},
        ),
        migrations.AlterModelOptions(
            name='monthlybudget',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Orçamento mensal', 'verbose_name_plural': 'Orçamentos mensais'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Movimento', 'verbose_name_plural': 'Movimentos'},
        ),
    ]
